### ISSUE TITLE
Deal with 'make gen' dependencies properly

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-goer#16] opened 2021-10-11 10:12 UTC
### Description

From @magnusbaeck :
To make it easier for users to get the right version of pigeon when building locally without using the dockerfile I think it's better to install the dependencies via the makefile and control the version via go.mod, but we can change that later.
https://github.com/eiffel-community/eiffel-goer/pull/15#discussion_r725520990

### Motivation

Easier for users to get the right version when building locally

**Comment by magnusbaeck** [comment] 2021-11-08 21:47
This is almost a duplicate of #6 so I'll widen the scope of that issue and fix the installation of all dependencies in one swoop and close this issue.

**Closed by magnusbaeck** 2021-11-08 21:47 UTC
